library(lubridate)
library(dplyr)
household<-read.csv("household_power_consumption.txt",sep=";",header = TRUE,na.strings = "?",colClasses = "character" )
household_set<-filter(household,(Date=="1/2/2007")|(Date=="2/2/2007"))
household_set$Global_active_power<-as.numeric(household_set$Global_active_power)
household_set<-mutate(household_set,datetime=paste(Date,Time,sep = " "))
household_set$datetime<-dmy_hms(household_set$datetime)

png(filename = "plot2.png",width = 480, height = 480, units = "px",bg = "transparent")
with(household_set,plot(datetime,Global_active_power,pch=".",xlab="",ylab = "Global Active Power (kilowatts)"))
lines(household_set$datetime,household_set$Global_active_power)
dev.off()